services:
  api-consult:
    image: api-enlace:latest
    container_name: backend-api-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - internalnet

networks:
  internalnet: