spring:
  application:
    name: ENLACE_DEV
  datasource:
    url: jdbc:h2:mem:enlace;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret:
    key: 8ebc070bb4a53120cd451cf58f4f48067decc4077a4b8d1f2a6632305cc4c299
  time:
    expiration: 86400000 # 1 day in milliseconds