server:
  port: 8080

spring:
  application:
    name: TWITTER
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  user:
    generator: ${JWT_USER_GENERATOR}